project:
    name: "Customer_Churn_Model_ANN"
    base_dir: "C:\\Aditya\\ML_Practice\\ML_Projects"

logging:
  log_dir: "logs"
  log_level: "INFO"
  log_format: '[%(asctime)s] %(lineno)d %(name)s - %(levelname)s - %(message)s'

data:
  source_type: "file"
  file_path: "C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\datasets\\Churn_Modelling_train.csv"
  file_format: "csv"
  read_params:
    encoding: "utf-8"

transformation:
  clean_steps:
    - name: drop_unwanted_cols
      params:
        drop_col: ['RowNumber','CustomerId','Surname']
    
    - name: fill_na
      params:
        targetcol: 'Exited'
  
  transform_steps:
    - name: fix_outliers
      params:
        numcols: ['Balance','EstimatedSalary']
        fix_mode: 'IQR'
        fix_type: 'clip'
        threshold: 1.5
eda:
  plot_data:
    - name: cat_dist_plot
      params: 
        base_folder: 'C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\artifacts'
        catcols: ['Geography','Gender']
    - name: num_dist_plot
      params:
        base_folder: 'C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\artifacts'
        numcols: ['CreditScore','Age','Tenure','Balance','EstimatedSalary']
    - name: correlation_plot
      params: 
        base_folder: 'C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\artifacts'
    - name: cat_tgt_plot
      params: 
        catcols: ['Geography','Gender']
        tgtcol: 'Exited'
        base_folder: 'C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\artifacts'

training:
  problem_type: 'Classification'
  target_column: 'Exited'

  train_test_split: 
    test_size: 0.2
    random_state: 42

  preprocessing:
    steps:
      - transformer: StandardScaler
        columns: ['CreditScore','Balance','EstimatedSalary']
        params: {}

      - transformer: OneHotEncoder
        columns: ['Geography','Gender']
        params:
          handle_unknown: 'ignore'
  
  model:
    name: 'ann'
    params:
      hidden_activation: relu
      output_activation: sigmoid
      hidden_nodes: 64
      output_nodes: 1
    compile:
      optimizer: 
        name: adam
        params:
          learning_rate: 0.01
      
      loss: binary_crossentropy

      metrics:
        - accuracy
    
      callbacks:
        - name : TensorBoard
          params:
            histogram_freq: 10
        - name : EarlyStopping
          params: 
            monitor: val_loss
            patience: 7
            restore_best_weights: True
    fit:
      epochs: 100  
    
  
  model_output:
    base_dir : "C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\models"
    model_logs : "C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\models\\model_logs\\fit"
    extension : h5