project:
    name: "Customer_Churn_Model_ANN"
    base_dir: "C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN"

logging:
  log_dir: "logs"
  log_level: "INFO"
  log_format: '[%(asctime)s] %(lineno)d %(name)s - %(levelname)s - %(message)s'

data:
  source_type: "file"
  file_path: "C:\\Aditya\\ML_Practice\\ML_Projects\\Customer_Churn_Model_ANN\\datasets\\Churn_Modelling_train.csv"
  file_format: "csv"
  read_params:
    encoding: "utf-8"