project:
    name: "Amazon_Reviews_Sentimment_Analysis"
    base_dir: "C:\\Aditya\\ML_Practice\\ML_Projects"

logging:
  log_dir: "logs"
  log_level: "INFO"
  log_format: '[%(asctime)s] %(lineno)d %(name)s - %(levelname)s - %(message)s'

data:
    train:
        source_type: file
        file_name: C:\Aditya\ML_Practice\ML_Projects\Amazon_Reviews_Sentimment_Analysis\datasets\amazon_reviews.csv
        file_extension: csv
        read_params: 
            encoding: 'utf-8'

transformation:
    clean_steps:
        - name: drop_unwanted_cols
          params: 
            drop_col: ['Unnamed: 0','reviewerName','reviewTime','day_diff','helpful_yes','helpful_no','total_vote','score_pos_neg_diff','score_average_rating', 'wilson_lower_bound']
        - name: fill_na
          params:
            targetcol: 'overall'
    transform_steps:
        - name: features_setting
          params:
            mappings:
                overall:
                    threshold: 3
                    positive_value: 1
                    negative_value: 0
                    operator: ">"
    text_preprocessing:
      preprocess_steps:
        - name: lower_text
          params: 
            col: reviewText
        - name: remove_special_characters
          params:
            col: reviewText
            search_pattern: "[^a-zA-z0-9]"
        - name: remove_white_spaces
          params:
            col: reviewText
            search_pattern: r"\s+""
        - name: handling_negations
          params:
            col: reviewText
            search_pattern: r"\bnot\s+(\w+)"
            replace_pattern: r"not_\1"
        - name: removing_emoji
          params:
            col: reviewText
        - name: removing_short_words
          params:
            col: reviewText
            word_length: 2
        - name: handling_url
          params:
            col: reviewText
            url_pattern: r"https\S+|www\S+"
            html_pattern: r"<.*?>"
training:
  type: Classification
  targetcol: overall

  tokenize:
    stop_words : english
